' La siguiente linia es para que al poner - delante de las clases para hacerlas privadas no te salga un cuadrado
skinparam classAttributeIconSize 0  
'Aqui se definen las clases
class Tienda
{
    -int CIF
    -string Ubicacion
    -string Nombre
}
class Equipo
{
    -Esquis Esquis
    -Gafas Gafas
    -Baston Bastones
}
class Cliente
{
    -string DNI
    -string Nombre
    -int Telefono
}
class Alquiler
{
    -int fechaAlquiler
    -int fechaDevolucion
}

class Esquis
{
    -string Marca
    -int NºSerie
}
class Gafas 
{
    -string Modelo
    -string Marca
    -int NºSerie
}
class Baston
{
    -string Modelo
    -string Marca
    -int NºSerie
}
class Marca
{
    -string Direccion
    -string Servicio
}
' Aqui se enlazan las clases
Tienda -- Equipo
Equipo -- Cliente
Cliente .. Alquiler
Equipo -- Esquis
Equipo -- Gafas
Equipo -- Baston
Esquis -- Marca
Gafas -- Marca
Baston -- Marca